[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "function Card:calculate_seal(context)"
position = "after"
payload = '''
    if context.cardarea == G.consumeables then
        return nil, true
    end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "if hand[i]:get_id() == hand[j]:get_id() and i ~= j then"
position = "at"
payload = '''
local lhs, rhs = hand[i]:get_id(), hand[j]:get_id()
if SMODS.has_enhancement(hand[i], 'm_folly_jimbo') then
  lhs = G.FUNCS.get_most_of_rank(hand)
end
if SMODS.has_enhancement(hand[j], 'm_folly_jimbo') then
  rhs = G.FUNCS.get_most_of_rank(hand)
end
if lhs == rhs and i ~= j then'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "vals[curr[1]:get_id()] = curr"
position = "at"
payload = '''
if SMODS.has_enhancement(curr[1], 'm_folly_jimbo') then
  vals[G.FUNCS.get_most_of_rank(hand)] = curr
else
  vals[curr[1]:get_id()] = curr
end'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "if hand[i]:is_suit(suit, nil, true) then flush_count = flush_count + 1;  t[#t+1] = hand[i] end"
position = "after"
payload = '''if SMODS.has_enhancement(hand[i], 'm_folly_jimbo') then
  flush_count = flush_count + 1
  t[#t+1] = hand[i]
end'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = 'function create_card(_type, area, legendary, _rarity, skip_materialize, soulable, forced_key, key_append)'
position = 'after'
payload = '''
local astro_funny = SMODS.find_card('j_folly_astronomer')
if _type == 'Planet' and next(astro_funny) then
    local astros = {}
    for i, v in pairs(astro_funny) do
        if v.ability.extra.astro then
            table.insert(astros, v.ability.extra.astro)
        end
    end
    if next(astros) then
        forced_key = pseudorandom_element(astros, pseudoseed('funny_astro'))
    end
end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'cardarea.lua'
pattern = "pseudoshuffle(self.cards, pseudoseed(_seed or 'shuffle'))"
position = 'after'
payload = '''
local obnoxious_cards = {}
for i = #self.cards, 1, -1 do
    if self.cards[i].seal == "folly_navy" then
        table.insert(obnoxious_cards, table.remove(self.cards, i))
    end
end
for _, v in pairs(obnoxious_cards) do
    table.insert(self.cards, v)
end
'''
match_indent = true


# chaos joker
# make pseudorandom not random
[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "function pseudorandom(seed, min, max)"
position = "after"
payload = '''
local chaos_jokers = SMODS.find_card('j_folly_chaos')
if next(chaos_jokers) then
    -- if multiple return max or 1
    if #chaos_jokers > 1 then
        if min and max then return max end
        return 1
    end
    -- if 1 return that chaos jokers preselected number
    if min and max then
        return math.floor(
            folly_utils.lerp(min, max, chaos_jokers[1].ability.random)
            )
    end
    return chaos_jokers[1].ability.random
end'''
match_indent = true
times = 1
