[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "function Card:calculate_seal(context)"
position = "after"
payload = '''
    if context.cardarea == G.consumeables then
        return nil, true
    end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "if hand[i]:get_id() == hand[j]:get_id() and i ~= j then"
position = "at"
payload = '''
local lhs, rhs = hand[i]:get_id(), hand[j]:get_id()
if SMODS.has_enhancement(hand[i], 'm_folly_jimbo') then
  lhs = G.FUNCS.get_most_of_rank(hand)
end
if SMODS.has_enhancement(hand[j], 'm_folly_jimbo') then
  rhs = G.FUNCS.get_most_of_rank(hand)
end
if lhs == rhs and i ~= j then'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "vals[curr[1]:get_id()] = curr"
position = "at"
payload = '''
if SMODS.has_enhancement(curr[1], 'm_folly_jimbo') then
  vals[G.FUNCS.get_most_of_rank(hand)] = curr
else
  vals[curr[1]:get_id()] = curr
end'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "if hand[i]:is_suit(suit, nil, true) then flush_count = flush_count + 1;  t[#t+1] = hand[i] end"
position = "after"
payload = '''if SMODS.has_enhancement(hand[i], 'm_folly_jimbo') then
  flush_count = flush_count + 1
  t[#t+1] = hand[i]
end'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = 'function create_card(_type, area, legendary, _rarity, skip_materialize, soulable, forced_key, key_append)'
position = 'after'
payload = '''
local astro_funny = SMODS.find_card('j_folly_astronomer')
if _type == 'Planet' and next(astro_funny) then
    local astros = {}
    for i, v in pairs(astro_funny) do
        if v.ability.extra.astro then
            table.insert(astros, v.ability.extra.astro)
        end
    end
    if next(astros) then
        forced_key = pseudorandom_element(astros, pseudoseed('funny_astro'))
    end
end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = 'G.GAME.dollars = G.GAME.dollars + mod'
position = 'after'
payload = '''
  for i = 1, #G.jokers.cards do
    local card = G.jokers.cards[i]
    local obj = card.config.center
    if obj.dollars_updated and type(obj.dollars_updated) == "function" then
      obj:dollars_updated(card, mod)
    end
  end
  if G.shop_jokers.cards then
    for i = 1, #G.shop_jokers.cards do
        local card = G.shop_jokers.cards[i]
        local obj = card.config.center
        if obj.set == "Joker" and obj.dollars_updated and type(obj.dollars_updated) == "function" then
            obj:folly_dollars_updated(card, mod)
        end
    end
  end
'''
match_indent = true
times = 1
