[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "function Card:calculate_seal(context)"
position = "after"
payload = '''
    if context.card_area == G.consumables then
        return nil, true
    end
'''
match_indent = true
times = 1